Repository gardener/gardener-custom-metrics, pull requests merged in 2024-03, with the labels that each got.

#7 Apply review comments. Add debug support
  .ci/pipeline_definitions
  Dockerfile
  Makefile
  README.md
  VERSION
  docs/development/README.md
  example/custom-metrics-deployment.yaml
  example/custom-metrics-service.yaml
  example/rbac.yaml
  go.mod
  go.sum
  hack/gardener-util/tools.mk
  pkg/app/cli_options.go
  pkg/ha/ha_service.go
  pkg/ha/ha_service_test.go
  pkg/input/controller/pod/predicate.go
  pkg/input/controller/secret/actuator.go
  pkg/input/controller/secret/predicate.go
  pkg/input/controller/secret/predicate_test.go
  pkg/input/input_data_service_test.go
  pkg/input/metrics_scraper/metrics_client.go
  pkg/input/metrics_scraper/pacemaker.go
  pkg/input/metrics_scraper/pacemaker_test.go
  pkg/input/metrics_scraper/scrape_queue_test.go
  pkg/input/metrics_scraper/scraper_test.go
  pkg/metrics_provider/metrics_provider.go
  pkg/metrics_provider/metrics_provider_service_test.go
  pkg/metrics_provider/metrics_provider_test.go
  pkg/util/gardener/options_test.go
  pkg/util/gardener/util.go
  pkg/util/gardener/util_test.go
  skaffold.yaml
Labels: area/auto-scaling, kind/enhancement, reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/l

#8 Drop the sigs.k8s.io/metrics-server dependency
  go.mod
  go.sum
  pkg/metrics_provider/metrics_provider_service.go
  vendor/k8s.io/metrics/pkg/apis/metrics/doc.go
  vendor/k8s.io/metrics/pkg/apis/metrics/install/install.go
  vendor/k8s.io/metrics/pkg/apis/metrics/register.go
  vendor/k8s.io/metrics/pkg/apis/metrics/types.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/doc.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/generated.pb.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/generated.proto
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/register.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/types.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/metrics/pkg/apis/metrics/zz_generated.deepcopy.go
  vendor/modules.txt
  vendor/sigs.k8s.io/metrics-server/LICENSE
  vendor/sigs.k8s.io/metrics-server/pkg/api/filter.go
  vendor/sigs.k8s.io/metrics-server/pkg/api/install.go
  vendor/sigs.k8s.io/metrics-server/pkg/api/interfaces.go
  vendor/sigs.k8s.io/metrics-server/pkg/api/monitoring.go
  vendor/sigs.k8s.io/metrics-server/pkg/api/node.go
  vendor/sigs.k8s.io/metrics-server/pkg/api/pod.go
  vendor/sigs.k8s.io/metrics-server/pkg/api/table.go
  vendor/sigs.k8s.io/metrics-server/pkg/api/time.go
Labels: area/auto-scaling, kind/cleanup, needs/ok-to-test, needs/review, size/s

#11 Fix `make verify`
  .docforge/manifest.yaml
  .github/workflows/release-milestone.yaml
  .gitignore
  Dockerfile
  Makefile
  example/custom-metrics-deployment.yaml
  example/image-pull-secret.yaml.tpl
  go.mod
  hack/gardener-util/check-docforge.sh
  hack/gardener-util/tools.mk
  pkg/app/cli_options.go
  pkg/input/input_data_service.go
  pkg/input/metrics_scraper/metrics_client.go
  pkg/input/metrics_scraper/metrics_client_test.go
  pkg/util/errutil/errutil.go
Labels: area/auto-scaling, kind/bug, needs/ok-to-test, needs/review, size/m

#10 Move from GCR to artifact registry
  .ci/pipeline_definitions
  Makefile
  cmd/gardener-custom-metrics/main.go
  example/custom-metrics-deployment.yaml
  hack/gardener-util/.ci/component_descriptor
  pkg/version/version.go
  skaffold.yaml
Labels: reviewed/lgtm, needs/ok-to-test, size/s

#15 Fix `make test`
  Makefile
Labels: area/dev-productivity, kind/bug, needs/ok-to-test, needs/review, size/xs
